name: kore_cli
description: Command line and interactive TUI frontend for Kore!? translation.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.12.2

executables:
  kore:

dependencies:
  args: ^2.7.0
  kore_client: ^0.1.0

dev_dependencies:
  kore_lints: ^0.1.0
