import 'dart:async';

import 'package:kore_client/src/exceptions.dart';
import 'package:kore_client/src/translation/translation_models.dart';
import 'package:kore_client/src/translation/translation_response_parser.dart';
import 'package:llm_json_stream/llm_json_stream.dart';

/// Streams provisional snapshots while the reply is being generated, then a
/// strictly parsed final result once [jsonDeltas] completes.
Stream<TranslationResult> translationResultStream(
  Stream<String> jsonDeltas,
) async* {
  final buffer = StringBuffer();
  yield* partialTranslationSnapshots(
    jsonDeltas.map((delta) {
      buffer.write(delta);
      return delta;
    }),
  );
  if (buffer.isEmpty) {
    throw const KoreClientException('The API reply contains no translation');
  }
  yield parseTranslationResponse(buffer.toString());
}

/// Subscribes to the JSON being generated by the LLM (via llm_json_stream)
/// and emits a provisional [TranslationResult] snapshot on every update.
///
/// The stream stays silent until the main translation starts, and closes when
/// [deltas] ends. Errors on [deltas] are forwarded as-is.
Stream<TranslationResult> partialTranslationSnapshots(Stream<String> deltas) {
  final output = StreamController<TranslationResult>();
  final input = StreamController<String>();
  final parser = JsonStreamParser(input.stream);
  final sniffer = _LeadingJsonSniffer();

  var translation = '';
  var detectedLanguage = '';
  var explanation = '';
  final alternatives = <TranslationCandidate>[];

  void emit() {
    if (translation.isEmpty || output.isClosed) {
      return;
    }
    output.add(
      TranslationResult(
        translation: translation,
        detectedLanguage: detectedLanguage,
        alternatives: List.of(alternatives),
        explanation: explanation,
      ),
    );
  }

  // Properties that never appear would error with "disposed before property
  // completed" on early termination, so chunk subscriptions ignore errors.
  void listenChunks(String path, void Function(String chunk) onChunk) {
    parser.getStringProperty(path).stream.listen(
      (chunk) {
        onChunk(chunk);
        emit();
      },
      onError: (Object _) {},
    );
  }

  listenChunks('translation', (chunk) => translation += chunk);
  listenChunks('detected_language', (chunk) => detectedLanguage += chunk);
  listenChunks('explanation', (chunk) => explanation += chunk);
  parser.getListProperty('alternatives').onElement((element, index) {
    alternatives.add(const TranslationCandidate(text: ''));
    void listenElementChunks(
      String key,
      TranslationCandidate Function(TranslationCandidate, String) apply,
    ) {
      element.asMap.getStringProperty(key).stream.listen(
        (chunk) {
          alternatives[index] = apply(alternatives[index], chunk);
          emit();
        },
        onError: (Object _) {},
      );
    }

    listenElementChunks(
      'text',
      (candidate, chunk) => candidate.copyWith(text: candidate.text + chunk),
    );
    listenElementChunks(
      'nuance',
      (candidate, chunk) => candidate.copyWith(nuance: candidate.nuance + chunk),
    );
  });

  deltas.listen(
    (delta) {
      final payload = sniffer.strip(delta);
      if (payload.isNotEmpty) {
        input.add(payload);
      }
    },
    onError: (Object error, StackTrace stackTrace) {
      output.addError(error, stackTrace);
    },
    onDone: () async {
      // parser.dispose() is intentionally not called: it completes the
      // futures of properties that never appeared with a StateError, which
      // would surface as unhandled errors (the library itself avoids dispose
      // in closeOnRootComplete for the same reason). Closing the input stops
      // the parser, and GC takes care of the rest.
      await input.close();
      await output.close();
    },
    cancelOnError: false,
  );

  return output.stream;
}

/// Drops everything before the JSON body (e.g. a leading ```` ```json ````
/// fence line). Our schema's root is always an object, so the body starts at
/// the first `{`.
class _LeadingJsonSniffer {
  var _found = false;

  String strip(String delta) {
    if (_found) {
      return delta;
    }
    final index = delta.indexOf('{');
    if (index == -1) {
      return '';
    }
    _found = true;
    return delta.substring(index);
  }
}
